apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: httpserver2
    spec:
      containers:
        - name: httpserver
          imagePullPolicy: Always
          image: puyuyang/golearning:chap10-metrics
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver2
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpserver2