apiVersion: apps/v1
kind: Deployment
metadata:
  name: cncamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cncamp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cncamp
    spec:
      containers:
      - name: cncamp-go-server
        image: puyuyang/golearning:chap03.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 4
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "90"]
        env:
        - name: VERSION
          value: 0.3.0
      imagePullSecrets:
      - name: github-eyblockchainregistry
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cncamp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cncamp